### ISSUE TITLE
clickable on loading

### ISSUE THREAD

**Issue by luckyraul** [mathieudutour/react-progress-button#1]
Hi. I get noticed that button is clickable and event fires once again in loading state

**Comment by mathieudutour** [comment]
will [this](https://github.com/mathieudutour/react-progress-button/pull/2) do?

**Comment by luckyraul** [comment]
I looked at your code and it is should be the thing I asked. 
Later I'll check it at my application.

**Comment by luckyraul** [comment]
ReferenceError: shouldAllowClickOnLoading is not defined
even with parameter defined

**Comment by mathieudutour** [comment]
my bad i should have tested

**Comment by mathieudutour** [comment]
done, react-progress-button@0.2.0 on npm

**Comment by luckyraul** [comment]
Good! 
I recommend you to remove hand icon mouse cursor over loading indicator.

**Comment by mathieudutour** [comment]
oh yeah good idea!

**Comment by mathieudutour** [comment]
done
