### ISSUE TITLE
“Invariant Violation: Element type is invalid:"

### ISSUE THREAD

**Issue by Coffee-Tea** [mathieudutour/react-progress-button#24]
I've got messages,  when require ("react-progress-button") and add to my component this variable.

Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `UploadSection`.
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `UploadSection`.

What could be the problem???

**Comment by mathieudutour** [comment]
what is your code?

**Comment by Coffee-Tea** [comment]
@mathieudutour here:
Thanks, but I've just solved the problem by adding ".default" to require.

```
"use strict";

var React = require('react');
var ProgressButton = require('react-progress-button').default;

var UploadSection = React.createClass({
    render: function() {
        return (
            <section id="portfolio">
                <div className="container">
                    <div className="row">
                        <div className="col-lg-12 text-center">
                            <h3>Try it out, upload you image</h3>
                            <hr className="star-primary" />
                            <ProgressButton>
                                Upload
                            </ProgressButton>
                        </div>
                    </div>
                </div>
            </section>
        );
    }   
});

module.exports = UploadSection;
```

maybe, you have some opinion about my case.

p.s. Thanks for this button :)

**Comment by mathieudutour** [comment]
Oh yeah, if you use `import ProgressButton from 'react-progress-button'`, you don't need `.default`
