### ISSUE TITLE
Change state to disabled

### ISSUE THREAD

**Issue by karladler** [mathieudutour/react-progress-button#46]
Changing state from `error` to `disabled`using prop types seems not to work for me. The state in the component is set correctly, but not the "currentState" so also not the container class and the onClick function is also available.

**Comment by karladler** [comment]
So I found the issue. Since I'm setting the state of the button to disabled, in the error callback, it's not working, because after the callback the state is set to STATE.NOTHING immediately. Is this the intentional behavior? Is there a nice way to solve this problem? (Currently I set the disabled state in error callback using timeout)

```
error (callback) {
    this.setState({currentState: STATE.ERROR})
    this._timeout = setTimeout(() => {
      callback = callback || this.props.onError
      if (typeof callback === 'function') { callback() }
      this.setState({currentState: STATE.NOTHING}) // this line makes me sad :(
    }, this.props.durationError)
  } 
```

**Comment by mathieudutour** [comment]
Sorry for the delay.

I think I fix this issue in https://github.com/mathieudutour/react-progress-button/commit/8dbcf8ce502d9a6afde9acb4ddc77ecdea9b00c1 but I don't really understand your use case so I'm not sure.

Could you test?
