### ISSUE TITLE
Can't prevent callback from triggered twice when double clicked

### ISSUE THREAD

**Issue by rutsoluo** [mathieudutour/react-progress-button#72]
When I double click, the callback is triggered twice and there is no way to to prevent it from happening.

I have tried to set the button state to disabled upon clicking but double click still trigger the callback twice.

**Comment by mathieudutour** [comment]
You can check in your callback when was the last time it was called. I'm not sure this should live in this component

**Comment by mathieudutour** [comment]
And there is this prop as well: `shouldAllowClickOnLoading`. Did you try using it?

**Comment by rutsoluo** [comment]
Hi Mathieu,

I set shouldAllowClickOnLoading to false and it still trigger the callback
twice, I will solve this in the callback itself.

Thanks

Rutso
