### ISSUE TITLE
CSS isn't loaded

### ISSUE THREAD

**Issue by MyrionPhoenixmoon** [mathieudutour/react-progress-button#73]
I installed the progress button as documented here and it looks ridiculous, because it is completely unstyled.

If I manually add the stylesheet to my site in devtools, the button works.

**Comment by MyrionPhoenixmoon** [comment]
The trick was to install css-loader and include
>      {
>        test: /\.css$/,
>        loader: "style!css"
>      }
in ```webpack.config.js``` and ```import "../node_modules/react-progress-button/react-progress-button.css";``` in the .jsx file.

**Comment by mathieudutour** [comment]
Do you want to add a section in the README with an webpack example?

Another solution (the one I'm using) if you are using `less` is to `@import "npm://react-progress-button/react-progress-button.css";` with https://github.com/less/less-plugin-npm-import

**Comment by MyrionPhoenixmoon** [comment]
Is that what you were thinking of? Hope it helps :)
