### ISSUE TITLE
How to change the height and the background color ?

### ISSUE THREAD

**Issue by ashishdhyani** [mathieudutour/react-progress-button#76]
How to change the Height and the background color ?
even if I change the style it is not getting impacted also the color is coming as black instead of blue as shown in demo.

               <ProgressButton 
                    onClick={this.onClick} 
                    state={this.props.progressState}
                    style={{width: '200px', height: '20px', "font-size": '8px'}}
                    >
                Populate Results
                </ProgressButton>

![image](https://cloud.githubusercontent.com/assets/21311351/24037422/b7a6396e-0b38-11e7-900c-76b52effa012.png)

success and error colors are shown properly.

**Comment by mathieudutour** [comment]
You can use CSS. Otherwise, the `style` props is applied to container. Maybe we need another props to apply styles to the different elements of the button?
Do you want to send a PR?

**Comment by togonow** [comment]
@mathieudutour can you elaborate more on how to do that.

**Comment by mathieudutour** [comment]
there is an example here: https://github.com/mathieudutour/react-progress-button/blob/master/react-progress-button.css
