### ISSUE TITLE
React.createClass is deprecated

### ISSUE THREAD

**Issue by luckyraul** [mathieudutour/react-progress-button#78]
ProgressButton: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by mathieudutour** [comment]
oh yeah, same for `propTypes`. Wants to throw a PR?

**Comment by luckyraul** [comment]
If I have time I won't create this issue. =(

This is just a notice to be done

**Comment by luckyraul** [comment]
I know it's super easy and fast.

**Comment by mathieudutour** [comment]
fixed in v5.0.3
